### PR TITLE
WIP Ruby 3.0.3

### PR DESCRIPTION
**Pull request by jaimeiniesta**
Let's support Ruby 3.

### CODE REVIEW

**Comment by jaimeiniesta** [comment]
There's a test failing in Ruby 3.0.1:

```
➔ bundle exec rspec ./spec/meta_inspector/meta_inspector_spec.rb:8
Run options: include {:focus=>true, :locations=>{"./spec/meta_inspector/meta_inspector_spec.rb"=>[8]}}

MetaInspector
  cache request (FAILED - 1)

Failures:

  1) MetaInspector cache request
     Failure/Error:
       response = session.get do |req|
         req.options.timeout      = @connection_timeout
         req.options.open_timeout = @read_timeout
       end
     
     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./lib/meta_inspector/request.rb:81:in `block in fetch'
     # ./lib/meta_inspector/request.rb:58:in `fetch'
     # ./lib/meta_inspector/request.rb:48:in `response'
     # ./lib/meta_inspector/request.rb:27:in `initialize'
     # ./lib/meta_inspector/document.rb:33:in `new'
     # ./lib/meta_inspector/document.rb:33:in `initialize'
     # ./lib/meta_inspector.rb:20:in `new'
     # ./lib/meta_inspector.rb:20:in `new'
     # ./spec/meta_inspector/meta_inspector_spec.rb:14:in `block (2 levels) in <top (required)>'

Finished in 0.11352 seconds (files took 1.16 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/meta_inspector/meta_inspector_spec.rb:8 # MetaInspector cache request
```

**Comment by jaimeiniesta** [comment]
@jschwindt there's a failing test that is blocking the upgrade to Ruby 3, and it's related to FaradayCache that we introduced [in this PR](https://github.com/metainspector/metainspector/pull/146)

Could you take a look please?

Here's how to make it fail:

```
➜  metainspector git:(ruby-3-0-3) bundle console
irb(main):001:0> cache = Hash.new
=> {}
irb(main):002:0>     def cache.read(k) self[k]; end
irb(main):003:0>     def cache.write(k, v) self[k] = v; end
=> :write
irb(main):004:0> MetaInspector.new('http://example.com', faraday_http_cache: { store: cache })

/Users/jaime/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:102:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

**Comment by jschwindt** [comment]
Done, all tests passing, ready to merge!

**Comment by jaimeiniesta** [comment]
Awesome @jschwindt thanks! 🚀

**Pull request merged**
