### PR TITLE
Update faraday and replace faraday_middleware

### PR DESCRIPTION
**Pull request by bruno-b-martins**
Hey there 👋 

First time contributing to this project, so feel free to point me in the right direction.

I have a conflict between `metainspector` and another gem I use on `faraday`'s version. Since the other gem is using the latest `faraday` version, I thought of updating `metainspector` to it as well.

So, `faraday (~> 2.0)` isn't supported by [faraday_middleware](https://github.com/lostisland/faraday_middleware) and this `faraday_middleware` is also deprecated for a while.
Thus, I've replaced `faraday_middleware` with `faraday-follow_redirects`, `faraday-gzip`, and `faraday-retry` according to the [upgrading guidelines](https://github.com/lostisland/faraday/blob/main/UPGRADING.md).

Can you please review and let me know if there's anything else to change?
Also, when everything's alright with the PR, can you please merge it and release a new version?

Thanks 🙇

### CODE REVIEW

**Comment by bruno-b-martins** [comment]
BTW, I've ran `rspec` against `master` and my branch, and both of them have 2 failing specs.

It's the "exception handling" `describe` block in https://github.com/metainspector/metainspector/blob/master/spec/request_spec.rb#L71.

I think the spec might be outdated according to this issue: https://github.com/lostisland/faraday/issues/702

**Comment by jaimeiniesta** [comment]
Hey, thanks a lot Bruno. I've had this upgrade of Faraday in the back of my mind for a while now, but I couldn't find the time to do that myself. So thanks!

What Ruby version are you using? With 3.0.3 tests works fine in my machine. Ruby 3.1 is not supported yet.

**Comment by bruno-b-martins** [comment]
You're welcome! Thanks for your effort in maintaining this.

Ah! That might be it, I'm using Ruby 3.1.2 already.

I can probably install Ruby 3.0.3 and see if they run through. Will update you shortly.

**Comment by jaimeiniesta** [comment]
PR looks good to me @bruno-b-martins - I'll approve it when CircleCI can confirm it works with the rest of Ruby versions (I tried with 3.0.3 and it went fine in my machine).

Regarding the failing specs in 3.1, it would be great to fix them so we can support the latest Ruby 😄

**Comment by bruno-b-martins** [comment]
Yup. Another time perhaps 😅

**Review by jaimeiniesta — APPROVED** [review]
LGTM 👍 

Thanks!

**Comment by jaimeiniesta** [comment]
OK so 5.13.0 is out with support for Ruby 3.1 - thanks @bruno-b-martins !!! 🎉

**Comment by bruno-b-martins** [comment]
Thank YOU @jaimeiniesta 🥳

**Pull request merged**
