### PR TITLE
Fix for empty base_url 

### PR DESCRIPTION
**Pull request by ishields**
Fix for https://github.com/metainspector/metainspector/issues/266

### CODE REVIEW

**Comment by jschwindt** [comment]
Hi @ishields! Thank you for you interest in MetaInspector and for sending this PR. Unfortunately a lot of tests are broken and it's becase the `#presence` method doesn’t exist in Ruby, it's part Rails Active Support Core Extensions that we are not including in this gem.

Please beside fixing the existing test also add some test that describes the problem with the empty base tag.

**Comment by jaimeiniesta** [comment]
Thanks for the PR @ishields ! Can you please include a test to cover this change?

**Comment by ishields** [comment]
@jaimeiniesta @jschwindt I've removed use of .presence .. I changed the method to use .strip and .empty? because they appear to be available even in early ruby.  I don't see what the minimum ruby version supported is defined.  I also added a test and made sure the whole suite was passing.   Let me know if you want anything tweaked or see a better way of doing this as you guys are a bit more familiar with everything.    

The original use case where I found this was here:
www.prismpilatescincinnati.com

**Comment by jaimeiniesta** [comment]
Thanks, I like that!

Ruby versions supported are defined in `.travis.yml`. I'll make that clearer on the README.

**Comment by jaimeiniesta** [comment]
Merged, thanks! 🎉

**Comment by jaimeiniesta** [comment]
Released in 5.10.1 🚀

**Pull request merged**
